### ISSUE TITLE
Support UISegmented Control

### ISSUE THREAD

**Issue by cruisediary** [RxSwiftCommunity/RxTheme#10]
How about supporting UISegmented Control?

**Comment by wddwycc** [comment]
@cruisediary for which attribute ?

**Comment by cruisediary** [comment]
@wddwycc  For tintColor like UIButton

**Comment by wddwycc** [comment]
@cruisediary 
Added in Version 2.1.3

**Comment by cruisediary** [comment]
@wddwycc thank you :) 👍
