### ISSUE TITLE
Free YouTube Video Tutorial

### ISSUE THREAD

**Issue by rebeloper** [RxSwiftCommunity/RxTheme#13]
Hi, I like RxTheme so much that I have decided to create a video tutorial about it!
You can take a look at it here: 

https://youtu.be/aV9qEcmJ7nY

Let me know what you think. If you like it consider adding the link with this image to your README. 

![Dark and Light Mode with RxTheme in Swift 5 and Xcode 10 2 Thubmnail](https://user-images.githubusercontent.com/2488011/55673846-23d58a00-58b6-11e9-9621-a799b6efb561.png)

**Comment by wddwycc** [comment]
@rebeloper 
Nice job bro.
Added to the README.
