### ISSUE TITLE
Adding SPM Support

### ISSUE THREAD

**Issue by pikabing** [RxSwiftCommunity/RxTheme#20]
Have you thought about adding SPM Support to the library rather than only cocoapods?

**Comment by chiragshenoy** [comment]
+1

**Comment by wddwycc** [comment]
I will take a look this weekend.

**Comment by pikabing** [comment]
I'll also try n raise a PR before the weekend :)

**Comment by wddwycc** [comment]
@pikabing @chiragshenoy I added SPM support, it's now usable in v5.0.4.

**Comment by chiragshenoy** [comment]
Awesome ! Thank you :)
