### ISSUE TITLE
RxTheme 6.0 ver error

### ISSUE THREAD

**Issue by JRJian** [RxSwiftCommunity/RxTheme#23]
<img width="1979" alt="image" src="https://user-images.githubusercontent.com/8022148/153137655-e2461446-9742-4873-981a-2fd2b9799874.png">

**Comment by omkar-sharechat** [comment]
`bind` API is removed in v6.0.0. 
Instead use,
`titleLabel.theme.textColor = themeService.attribute { $0.text }`
