### ISSUE TITLE
Why we can't bind more than 2 properties?

### ISSUE THREAD

**Issue by tosbaha** [RxSwiftCommunity/RxTheme#6]
Hi,
If I do something like this
```swift
        themeService.bind([
            ({ $0.backgroundColor }, [self.rx.backgroundColor]),
            ({ $0.textLabelColor }, [self.textLabel!.rx.textColor]),
            ({ $0.detailTextLabelColor }, [self.detailTextLabel!.rx.textColor])
            ]).disposed(by: disposeBag)
```
Compiler gives me `Type of expression is ambiguous without more context` error. If I delete anyone of them, it compiles. Is it Swift bug or by design? What is the proper way to bind 3,4 properties all once instead of binding 2 or 1 at a time. Thanks.

**Comment by wddwycc** [comment]
@tosbaha 
This is a known issue for me, the compiler sometimes would consider the binding syntax as too complex. 
I'd prefer optimize it in the next version.

**Comment by tosbaha** [comment]
@wddwycc Thanks for the answer. I am looking forward to your next version.

**Comment by wddwycc** [comment]
@tosbaha Resolved in version2.0 with new chaining syntax
